app:
  jwt:
   access:
     secret: ""
  admin:
    password: ""
  otp:
    duration: 5
spring:
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=BD20230209RCC;trustServerCertificate=true
    # set your own credentials
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: sql_server
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
